(()=>{'use strict';
const K='bcl.clean.v4';
const ENDPOINT='https://rxwlcwziuhtlujdmjwom.supabase.co/functions/v1/analysiscore-builder-v2';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4d2xjd3ppdWh0bHVqZG1qd29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDgwMzMsImV4cCI6MjEwMjUyNDAzM30.EIFJXVhKlIyOcfcYPmiz4ct10iTpMqe_Dk4Jal49ChU';
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:(typeof v==='string'&&v.trim()?v.split(',').map(x=>x.trim()).filter(Boolean):[]);
const seed=()=>({version:4,context:{className:'Test',spec:'Awakening'},skills:{Test:{Awakening:[{name:'Engage Step',phase:'engagement',pveDamage:420,pvpDamage:280,duration:.55,cooldown:4,cc:[],protection:'Super Armor',enabled:true},{name:'Raven Crescent',phase:'cc',pveDamage:1572,pvpDamage:1030,duration:1.1,cooldown:7,cc:['Stun'],ccAt:.72,enabled:true},{name:'Broken Torrent',phase:'burst',pveDamage:4584,pvpDamage:3025,duration:1.25,cooldown:9,cc:[],protection:'Forward Guard',enabled:true},{name:'Silent Bane',phase:'finish',pveDamage:3320,pvpDamage:2180,duration:1.05,cooldown:8,cc:['Bound'],ccAt:.65,enabled:true}],Succession:[]}},transitions:{Test:{Awakening:[{from:'Engage Step',to:'Raven Crescent',timingSeconds:.18,cancelAt:.42,entryOffset:.18,reviewStatus:'validated',enabled:true},{from:'Raven Crescent',to:'Broken Torrent',timingSeconds:.14,cancelAt:.86,entryOffset:.32,reviewStatus:'validated',enabled:true},{from:'Broken Torrent',to:'Silent Bane',timingSeconds:.16,cancelAt:.74,entryOffset:.12,reviewStatus:'pending',needsValidation:true,enabled:true}],Succession:[]}},combos:{Test:{Awakening:[{name:'Starter PvP route',orientation:'PvP',sequence:['Engage Step','Raven Crescent','Broken Torrent','Silent Bane']}],Succession:[]}},addons:{Test:{Awakening:[],Succession:[]}},builder:{Test:{Awakening:[],Succession:[]}},videoMarkers:[],prefs:{profile:'balanced',searchDepth:'standard',maxComboSkills:10,combatMode:'pvp',strictCC:true,ccFocus:'high',damageFocus:'balanced',protectionPriority:'medium',protectionGaps:'avoid',timingTolerance:'normal',transitionPolicy:'measured',cancelPolicy:'measured',resourceDiscipline:'balanced',staminaReserve:'medium',resourceReserve:'medium',confidence:'medium',missingData:'cautious',adviceStyle:'detailed'}});
function normalize(raw){const f=seed(),s=raw&&typeof raw==='object'?raw:f;s.version=4;s.context={...f.context,...(s.context||{})};for(const k of ['skills','transitions','combos','addons','builder'])if(!s[k]||typeof s[k]!=='object')s[k]={};if(!Array.isArray(s.videoMarkers))s.videoMarkers=[];s.prefs={...f.prefs,...(s.prefs||{})};return s}
function load(){for(const key of [K,'bcl.clean.v3','bcl.clean.v2','bcl.clean.v1']){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x)return normalize(x)}catch(_){}}return seed()}
let S=load(),page='home',suggestions=[],coach=[];
function save(){S.version=4;try{localStorage.setItem(K,JSON.stringify(S))}catch(e){runtimeError(e)}}
function ensure(cls=S.context.className,spec=S.context.spec){for(const k of ['skills','transitions','combos','addons','builder']){S[k]??={};S[k][cls]??={Awakening:[],Succession:[]};if(!Array.isArray(S[k][cls][spec]))S[k][cls][spec]=[]}}
const list=k=>(ensure(),S[k][S.context.className][S.context.spec]);
const skills=()=>list('skills'), trs=()=>list('transitions'), combos=()=>list('combos'), addons=()=>list('addons'), seq=()=>list('builder');
function runtimeError(e){console.error('[BCL V4]',e);const h=$('#appHealth');if(h){h.textContent='Runtime error';h.className='status-pill bad';h.title=e?.message||String(e)}}
window.addEventListener('error',e=>runtimeError(e.error||new Error(e.message)));window.addEventListener('unhandledrejection',e=>runtimeError(e.reason||new Error('Promise rejected')));
function metric(a,b){return `<div class="metric"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`}
function status(t){const s=String(t?.reviewStatus||'').toLowerCase();return ['validated','corrected','rejected'].includes(s)?s:(t?.needsValidation?'pending':'manual')}
function go(p){page=p;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));render(p)}
function renderContext(){const names=new Set(['Test',...Object.keys(S.skills||{}),...Object.keys(S.transitions||{}),...Object.keys(S.combos||{})]);if(!names.has(S.context.className))S.context.className=[...names][0]||'Test';const c=$('#classSelector');if(c)c.innerHTML=[...names].sort().map(n=>`<option value="${esc(n)}" ${n===S.context.className?'selected':''}>${esc(n)}</option>`).join('');const s=$('#specSelector');if(s)s.value=S.context.spec;ensure()}
function renderHome(){const t=trs();$('#overviewMetrics').innerHTML=metric('Skills',skills().length)+metric('Transitions',t.length)+metric('Approved timings',t.filter(x=>['validated','corrected'].includes(status(x))).length)+metric('Class combos',combos().length)+metric('Current combo',seq().length);$('#overviewFocus').textContent=`${S.context.className} · ${S.context.spec} · ${String(S.prefs.combatMode).toUpperCase()} · ${S.prefs.profile} profile`}
function renderSkills(){const h=$('#skillsTable'),d=skills();if(!d.length){h.innerHTML='<div class="empty">No skills registered.</div>';return}h.innerHTML='<div class="rows">'+d.map((s,i)=>`<article class="row"><div class="row-title"><strong>${esc(s.name||'Unnamed')}</strong><small>${esc(s.phase||'unclassified')} · ${esc(arr(s.cc).join(', ')||'No CC')}</small></div><div class="cell"><span>PvE damage</span><b>${num(s.pveDamage??s.damage)||'—'}</b></div><div class="cell"><span>PvP damage</span><b>${num(s.pvpDamage)||'—'}</b></div><div class="cell"><span>Duration</span><b>${num(s.duration)?num(s.duration).toFixed(3)+' s':'—'}</b></div><div class="actions"><button data-add="${i}">Add to combo</button><button data-edit="${i}">Edit</button><button data-del="${i}" class="danger">Delete</button></div></article>`).join('')+'</div>'}
function renderCombos(){const h=$('#classCombosList'),d=combos();if(!d.length){h.innerHTML='<div class="empty">No class combos registered.</div>';return}h.innerHTML=d.map((c,i)=>`<article class="row"><div class="row-title"><strong>${esc(c.name||'Combo')}</strong><small>${esc(c.orientation||'Mixed')}</small></div><div class="cell" style="grid-column:span 3"><span>Sequence</span><b>${esc(arr(c.sequence).join(' → '))}</b></div><div class="actions"><button data-load="${i}">Load</button><button data-edit="${i}">Edit</button><button data-del="${i}" class="danger">Delete</button></div></article>`).join('')}
function renderTransitions(){const d=trs(),sum=$('#transitionSummary'),h=$('#transitionList');sum.innerHTML=metric('Entries',d.length)+metric('Approved',d.filter(x=>['validated','corrected'].includes(status(x))).length)+metric('Pending',d.filter(x=>status(x)==='pending').length)+metric('Rejected',d.filter(x=>status(x)==='rejected').length)+metric('Active',d.filter(x=>x.enabled!==false).length);if(!d.length){h.innerHTML='<div class="empty">No transitions or cancels registered.</div>';return}h.innerHTML=d.map((t,i)=>{const s=status(t);return `<article class="row"><div class="row-title"><strong>${esc(t.from||t.fromSkill||'?')} → ${esc(t.to||t.toSkill||'?')}</strong><small>${esc(t.kind||t.transitionType||'transition')}</small></div><div class="cell"><span>Transition</span><b>${t.timingSeconds!=null?num(t.timingSeconds).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Cancel point</span><b>${t.cancelAt!=null?num(t.cancelAt).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Entry skip</span><b>${t.entryOffset!=null?num(t.entryOffset).toFixed(4)+' s':'—'}</b></div><div class="actions"><span class="status-pill ${s==='rejected'?'bad':s==='pending'?'warn':['validated','corrected'].includes(s)?'good':''}">${esc(s)}</span><button data-v="${i}">Validate</button><button data-c="${i}">Correct</button><button data-r="${i}" class="danger">Reject</button></div></article>`}).join('')}
function renderVideo(){const h=$('#videoMarkers'),d=S.videoMarkers;if(!d.length){h.innerHTML='<div class="empty">No timing markers yet.</div>';return}h.innerHTML=d.map((x,i)=>`<article class="row"><div class="row-title"><strong>${esc(x.type)}</strong><small>Frame ${x.frame} @ ${x.fps} FPS</small></div><div class="cell"><span>Timestamp</span><b>${num(x.time).toFixed(4)} s</b></div><div class="cell" style="grid-column:span 2"><span>Use</span><b>${esc(x.note||'Attach this event to a skill or transition.')}</b></div><div class="actions"><button data-del-marker="${i}" class="danger">Delete</button></div></article>`).join('')}
function renderAddons(){const h=$('#addonList'),d=addons();if(!d.length){h.innerHTML='<div class="empty">No skill add-ons registered.</div>';return}h.innerHTML=d.map((a,i)=>`<article class="row"><div class="row-title"><strong>${esc(a.skill||'Skill')}</strong><small>${esc(a.label||'Add-on')}</small></div><div class="cell" style="grid-column:span 3"><span>Effect</span><b>${esc(a.effect||'—')}</b></div><div class="actions"><button data-edit-addon="${i}">Edit</button><button data-del-addon="${i}" class="danger">Delete</button></div></article>`).join('')}
function findSkill(n){return skills().find(s=>String(s.name).toLowerCase()===String(n).toLowerCase())}
function renderBuilder(){const q=seq(),ss=q.map(findSkill).filter(Boolean),damage=ss.reduce((a,s)=>a+num(S.prefs.combatMode==='pve'?(s.pveDamage??s.damage):s.pvpDamage),0),duration=ss.reduce((a,s)=>a+Math.max(.01,num(s.duration,.5)),0);$('#builderStats').innerHTML=[['Skills',q.length],['Damage',Math.round(damage)],['Duration',duration.toFixed(3)+' s'],['Estimated DPS',duration?Math.round(damage/duration):0],['CC effects',ss.reduce((a,s)=>a+arr(s.cc).length,0)],['Protection',ss.length?Math.round(ss.filter(s=>s.protection).length/ss.length*100)+'%':'0%']].map(x=>`<div class="stat-cell"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#comboSequence').innerHTML=q.length?q.map((n,i)=>`<span class="skill-chip">${i+1}. ${esc(n)}<button data-x="${i}">×</button></span>`).join(''):'<span class="empty" style="width:100%">Add skills or let AnalysisCore build a route.</span>';renderSuggestions();renderCoach()}
function renderSuggestions(){const h=$('#suggestions');if(!suggestions.length){h.innerHTML='<div class="empty">Run AnalysisCore to get suggestions.</div>';return}h.innerHTML=suggestions.slice(0,8).map((s,i)=>`<article class="row" style="grid-template-columns:1fr 110px 130px"><div class="row-title"><strong>${i+1}. ${esc(s.skill||s.name||'Skill')}</strong><small>${esc(s.phase||'')} · score ${Number.isFinite(Number(s.score))?Number(s.score).toFixed(3):'—'}</small></div><div class="cell"><span>Damage</span><b>${Math.round(num(s.metrics?.damage))||'—'}</b></div><div class="actions"><button data-suggest-add="${i}">Add</button></div></article>`).join('')}
function renderCoach(){const h=$('#coach');if(!coach.length){h.innerHTML=`<div class="coach-item"><strong>${String(S.prefs.combatMode).toUpperCase()} · ${esc(S.prefs.profile)}</strong><p>Coach uses active settings: damage ${esc(S.prefs.damageFocus)}, protection ${esc(S.prefs.protectionPriority)}, timing ${esc(S.prefs.timingTolerance)}, CC ${S.prefs.strictCC?'strict':'flexible'}.</p></div>`;return}h.innerHTML=coach.map(x=>`<div class="coach-item"><strong>${esc(x.title||x.kind||'Advice')}</strong><p>${esc(x.text||x.message||String(x))}</p></div>`).join('')}
const presets={balanced:{profile:'balanced',combatMode:'pvp',strictCC:true,damageFocus:'balanced',ccFocus:'high',protectionPriority:'medium',timingTolerance:'normal'},'pvp-safe':{profile:'safe',combatMode:'pvp',strictCC:true,damageFocus:'balanced',ccFocus:'high',protectionPriority:'strict',timingTolerance:'tight'},'pvp-burst':{profile:'aggressive',combatMode:'pvp',strictCC:true,damageFocus:'high',ccFocus:'high',protectionPriority:'medium',timingTolerance:'tight'},'pve-dps':{profile:'dps',combatMode:'pve',strictCC:false,damageFocus:'maximum',ccFocus:'low',protectionPriority:'low',timingTolerance:'normal'}};
const settingGroups=[
 ['Mode & search',[['combatMode','Combat mode',['pvp','pve']],['profile','Analysis profile',['balanced','safe','aggressive','dps']],['searchDepth','Search depth',['fast','standard','deep']],['maxComboSkills','Maximum combo skills','number']]],
 ['Combat priorities',[['damageFocus','Damage focus',['low','balanced','high','maximum']],['ccFocus','CC focus',['low','medium','high']],['protectionPriority','Protection priority',['low','medium','strict']],['strictCC','Strict CC','boolean']]],
 ['Timing & transitions',[['timingTolerance','Timing tolerance',['loose','normal','tight']],['transitionPolicy','Transition policy',['all','measured','validated']],['cancelPolicy','Cancel policy',['all','measured','validated']],['protectionGaps','Protection gaps',['allow','avoid','strict']]],
 ['Resources & confidence',[['resourceDiscipline','Resource discipline',['relaxed','balanced','strict']],['staminaReserve','Stamina reserve',['low','medium','high']],['resourceReserve','Resource reserve',['low','medium','high']],['confidence','Minimum confidence',['low','medium','high']],['missingData','Missing data',['permissive','cautious','strict']],['adviceStyle','Coach style',['concise','detailed','technical']]]
];
function settingControl(k,type){const v=S.prefs[k];if(type==='boolean')return `<input data-setting="${k}" type="checkbox" ${v?'checked':''}>`;if(type==='number')return `<input data-setting="${k}" type="number" min="1" max="30" value="${num(v,10)}">`;return `<select data-setting="${k}">${type.map(x=>`<option value="${x}" ${x===v?'selected':''}>${x}</option>`).join('')}</select>`}
function renderSettings(){const h=$('#settingsForm');h.innerHTML=settingGroups.map(([title,rows])=>`<section class="setting-group"><h2>${title}</h2>${rows.map(([k,label,type])=>`<label class="setting-row"><span>${label}</span>${settingControl(k,type)}</label>`).join('')}</section>`).join('')}
function render(p){try{({home:renderHome,skills:renderSkills,classCombos:renderCombos,transitions:renderTransitions,video:renderVideo,addons:renderAddons,builder:renderBuilder,settings:renderSettings}[p]||(()=>{}))()}catch(e){runtimeError(e)}}
function dialog(title,fields,onSave){const d=$('#editorDialog'),box=$('#editorFields'),form=$('#editorForm');$('#editorTitle').textContent=title;box.innerHTML=fields.map(f=>`<label class="${f.wide?'wide':''}">${esc(f.label)}${f.type==='textarea'?`<textarea name="${f.name}">${esc(f.value??'')}</textarea>`:`<input name="${f.name}" type="${f.type||'text'}" step="any" value="${esc(f.value??'')}">`}</label>`).join('');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));onSave(fd);d.close()};d.showModal()}
function editSkill(i=null){const d=skills(),s=i==null?{}:d[i];dialog(i==null?'Add skill':'Edit skill',[{name:'name',label:'Name',value:s.name},{name:'phase',label:'Combat phase',value:s.phase},{name:'pveDamage',label:'PvE damage',type:'number',value:s.pveDamage},{name:'pvpDamage',label:'PvP damage',type:'number',value:s.pvpDamage},{name:'duration',label:'Duration (s)',type:'number',value:s.duration},{name:'cooldown',label:'Cooldown (s)',type:'number',value:s.cooldown},{name:'cc',label:'CC types, comma separated',value:arr(s.cc).join(', ')},{name:'ccAt',label:'CC applies at (s)',type:'number',value:s.ccAt},{name:'protection',label:'Protection',value:s.protection}],fd=>{const x={...s,...fd,pveDamage:num(fd.pveDamage),pvpDamage:num(fd.pvpDamage),duration:num(fd.duration),cooldown:num(fd.cooldown),cc:arr(fd.cc),ccAt:fd.ccAt===''?null:num(fd.ccAt),enabled:true};i==null?d.push(x):d[i]=x;save();renderSkills();renderHome()})}
function editTransition(i=null,correct=false){const d=trs(),t=i==null?{}:d[i];dialog(i==null?'Add transition':correct?'Correct transition':'Edit transition',[{name:'from',label:'From skill',value:t.from||t.fromSkill},{name:'to',label:'To skill',value:t.to||t.toSkill},{name:'timingSeconds',label:'Transition duration (s)',type:'number',value:t.timingSeconds},{name:'cancelAt',label:'Cancel point (s)',type:'number',value:t.cancelAt},{name:'entryOffset',label:'Entry skip (s)',type:'number',value:t.entryOffset},{name:'kind',label:'Type',value:t.kind||t.transitionType||'transition'}],fd=>{const x={...t,from:fd.from,to:fd.to,timingSeconds:fd.timingSeconds===''?null:num(fd.timingSeconds),cancelAt:fd.cancelAt===''?null:num(fd.cancelAt),entryOffset:fd.entryOffset===''?null:num(fd.entryOffset),kind:fd.kind,enabled:true,reviewStatus:correct?'corrected':(t.reviewStatus||'pending'),needsValidation:!correct,manualValidation:!!correct,reviewedAt:new Date().toISOString()};i==null?d.push(x):d[i]=x;save();renderTransitions()})}
function editCombo(i=null){const d=combos(),c=i==null?{}:d[i];dialog(i==null?'Add combo':'Edit combo',[{name:'name',label:'Name',value:c.name},{name:'orientation',label:'Orientation',value:c.orientation||'PvP'},{name:'sequence',label:'Sequence, comma separated',wide:true,value:arr(c.sequence).join(', ')}],fd=>{const x={...c,name:fd.name,orientation:fd.orientation,sequence:arr(fd.sequence)};i==null?d.push(x):d[i]=x;save();renderCombos()})}
function editAddon(i=null){const d=addons(),a=i==null?{}:d[i];dialog(i==null?'Add skill add-on':'Edit skill add-on',[{name:'skill',label:'Skill',value:a.skill},{name:'label',label:'Label',value:a.label},{name:'effect',label:'Effect',wide:true,value:a.effect}],fd=>{const x={...a,...fd};i==null?d.push(x):d[i]=x;save();renderAddons()})}
function review(i,s){const t=trs()[i];if(!t)return;t.reviewStatus=s;t.needsValidation=false;t.manualValidation=s==='validated';t.enabled=s!=='rejected';t.reviewedAt=new Date().toISOString();save();renderTransitions()}
function mark(type){const v=$('#timingVideo'),fps=Math.max(1,num($('#videoFps')?.value,60)),time=num(v?.currentTime);S.videoMarkers.push({type,time,frame:Math.round(time*fps),fps});save();renderVideo()}
async function analysis(action){const st=$('#analysisStatus');if(st){st.textContent='AnalysisCore running…';st.className='status-pill warn'}try{const body={action,skills:skills().filter(s=>s.enabled!==false),transitions:trs().filter(t=>t.enabled!==false),prefix:[...seq()],preferences:S.prefs,limit:8};const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':ANON,'authorization':'Bearer '+ANON},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok===false)throw new Error(data.error||`HTTP ${r.status}`);if(action==='suggest')suggestions=Array.isArray(data.suggestions)?data.suggestions:[];else{const best=(data.results||[]).find(x=>Array.isArray(x.sequence));if(best){const q=seq();q.splice(0,q.length,...best.sequence);save()}suggestions=Array.isArray(data.suggestions)?data.suggestions:[]}coach=Array.isArray(data.coach)?data.coach:Array.isArray(data.advice)?data.advice:[];if(st){st.textContent=`AnalysisCore · ${String(S.prefs.combatMode).toUpperCase()} · ${S.prefs.profile}`;st.className='status-pill good'}renderBuilder()}catch(e){if(st){st.textContent='AnalysisCore: '+e.message;st.className='status-pill bad'}runtimeError(e)}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.closest('#nav'))return go(b.dataset.page);if(b.id==='addSkillBtn')return editSkill();if(b.id==='addComboBtn')return editCombo();if(b.id==='addTransitionBtn')return editTransition();if(b.id==='addAddonBtn')return editAddon();if(b.id==='clearComboBtn'){seq().splice(0);save();return renderBuilder()}if(b.id==='suggestBtn')return analysis('suggest');if(b.id==='completeBtn')return analysis('complete');if(b.id==='markTransitionBtn')return mark('transition');if(b.id==='markCcBtn')return mark('cc');if(b.id==='markDamageBtn')return mark('damage');if(b.id==='clearMarkersBtn'){S.videoMarkers=[];save();return renderVideo()}if(b.dataset.add!=null&&b.closest('#skillsTable')){seq().push(skills()[+b.dataset.add].name);save();return go('builder')}if(b.dataset.edit!=null&&b.closest('#skillsTable'))return editSkill(+b.dataset.edit);if(b.dataset.del!=null&&b.closest('#skillsTable')){skills().splice(+b.dataset.del,1);save();return renderSkills()}if(b.dataset.load!=null&&b.closest('#classCombosList')){const c=combos()[+b.dataset.load];seq().splice(0,seq().length,...arr(c.sequence));save();return go('builder')}if(b.dataset.edit!=null&&b.closest('#classCombosList'))return editCombo(+b.dataset.edit);if(b.dataset.del!=null&&b.closest('#classCombosList')){combos().splice(+b.dataset.del,1);save();return renderCombos()}if(b.dataset.v!=null)return review(+b.dataset.v,'validated');if(b.dataset.r!=null)return review(+b.dataset.r,'rejected');if(b.dataset.c!=null)return editTransition(+b.dataset.c,true);if(b.dataset.x!=null){seq().splice(+b.dataset.x,1);save();return renderBuilder()}if(b.dataset.suggestAdd!=null){const s=suggestions[+b.dataset.suggestAdd];if(s?.skill){seq().push(s.skill);save();renderBuilder()}return}if(b.dataset.delMarker!=null){S.videoMarkers.splice(+b.dataset.delMarker,1);save();return renderVideo()}if(b.dataset.editAddon!=null)return editAddon(+b.dataset.editAddon);if(b.dataset.delAddon!=null){addons().splice(+b.dataset.delAddon,1);save();return renderAddons()}const p=b.dataset.preset;if(p){Object.assign(S.prefs,presets[p]||{});save();$$('#presetBar button').forEach(x=>x.classList.toggle('active',x.dataset.preset===p));renderSettings();renderBuilder()}});const cf=$('#classSelector'),sf=$('#specSelector'),vf=$('#videoFile'),settings=$('#settingsForm');if(cf)cf.onchange=e=>{S.context.className=e.target.value;ensure();save();renderContext();render(page)};if(sf)sf.onchange=e=>{S.context.spec=e.target.value;ensure();save();render(page)};if(vf)vf.onchange=e=>{const f=e.target.files?.[0];if(f)$('#timingVideo').src=URL.createObjectURL(f)};if(settings)settings.onchange=e=>{const el=e.target.closest('[data-setting]');if(!el)return;const k=el.dataset.setting;S.prefs[k]=el.type==='checkbox'?el.checked:el.type==='number'?num(el.value):el.value;save();renderBuilder()}}
function init(){try{renderContext();bind();go('home');const h=$('#appHealth');if(h){h.textContent='Ready · V4';h.className='status-pill good'}}catch(e){runtimeError(e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();