(()=>{'use strict';
const K='bcl.clean.v3';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const seed=()=>({version:3,context:{className:'Test',spec:'Awakening'},skills:{Test:{Awakening:[
{name:'Engage Step',phase:'engagement',pveDamage:420,pvpDamage:280,duration:.55,cooldown:4,damageAt:.32,cc:[],protection:'Super Armor',staminaCost:100,resourceCost:0,mobility:'forward',specialAttacks:[],buffs:[],debuffs:[],notes:'',enabled:true},
{name:'Raven Crescent',phase:'cc',pveDamage:1572,pvpDamage:1030,duration:1.1,cooldown:7,damageAt:.68,cc:['Stun'],ccAt:.72,protection:'',staminaCost:0,resourceCost:20,mobility:'',specialAttacks:['Down Attack'],buffs:[],debuffs:[],notes:'',enabled:true},
{name:'Broken Torrent',phase:'burst',pveDamage:4584,pvpDamage:3025,duration:1.25,cooldown:9,damageAt:.48,cc:[],protection:'Forward Guard',staminaCost:0,resourceCost:35,mobility:'',specialAttacks:['Down Attack'],buffs:[],debuffs:[],notes:'',enabled:true},
{name:'Silent Bane',phase:'finish',pveDamage:3320,pvpDamage:2180,duration:1.05,cooldown:8,damageAt:.56,cc:['Bound'],ccAt:.65,protection:'',staminaCost:0,resourceCost:30,mobility:'',specialAttacks:['Air Attack'],buffs:[],debuffs:[],notes:'',enabled:true}
],Succession:[]}},transitions:{Test:{Awakening:[
{from:'Engage Step',to:'Raven Crescent',timingSeconds:.18,cancelAt:.42,entryOffset:.18,kind:'cancel',confidence:.95,fps:60,frames:11,condition:'',protection:'',reviewStatus:'validated',enabled:true},
{from:'Raven Crescent',to:'Broken Torrent',timingSeconds:.14,cancelAt:.86,entryOffset:.32,kind:'cancel',confidence:.92,fps:60,frames:8,condition:'',protection:'',reviewStatus:'validated',enabled:true},
{from:'Broken Torrent',to:'Silent Bane',timingSeconds:.16,cancelAt:.74,entryOffset:.12,kind:'transition',confidence:.75,fps:60,frames:10,condition:'',protection:'',reviewStatus:'pending',needsValidation:true,enabled:true}
],Succession:[]}},combos:{Test:{Awakening:[],Succession:[]}},addons:{Test:{Awakening:[],Succession:[]}},builder:{Test:{Awakening:[],Succession:[]}},videoMarkers:[],prefs:{profile:'balanced',searchDepth:'standard',maxComboSkills:10,combatMode:'pvp',strictCC:true,ccFocus:'high',damageFocus:'balanced',specialAttackFocus:'balanced',cooldownTolerance:'medium',smashUsage:'situational',wastedCC:'avoid',protectionPriority:'medium',protectionGaps:'avoid',timingTolerance:'normal',transitionPolicy:'measured',cancelPolicy:'measured',resourceDiscipline:'balanced',staminaReserve:'medium',resourceReserve:'medium',confidence:'medium',missingData:'cautious',adviceStyle:'detailed'}});
function load(){for(const k of [K,'bcl.clean.v2','bcl.clean.v1'])try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x)return x}catch(_){}return seed()}
let S=load(),page='home';
function norm(){const f=seed();S.context={...f.context,...(S.context||{})};for(const k of ['skills','transitions','combos','addons','builder'])S[k]=S[k]&&typeof S[k]==='object'?S[k]:{};S.prefs={...f.prefs,...(S.prefs||{})};S.videoMarkers=Array.isArray(S.videoMarkers)?S.videoMarkers:[]}
norm();
function save(){S.version=3;localStorage.setItem(K,JSON.stringify(S))}
function ensure(){const c=S.context.className,s=S.context.spec;for(const k of ['skills','transitions','combos','addons','builder']){S[k][c]??={Awakening:[],Succession:[]};S[k][c][s]=Array.isArray(S[k][c][s])?S[k][c][s]:[]}}
const L=k=>(ensure(),S[k][S.context.className][S.context.spec]),skills=()=>L('skills'),trs=()=>L('transitions'),combos=()=>L('combos'),addons=()=>L('addons'),seq=()=>L('builder');
function go(p){page=p;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));render(p)}
function metric(a,b){return `<div class="metric"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`}
function st(t){const s=String(t?.reviewStatus||'').toLowerCase();return ['validated','corrected','rejected'].includes(s)?s:(t?.needsValidation?'pending':'manual')}
function context(){const names=new Set(['Test',...Object.keys(S.skills),...Object.keys(S.transitions),...Object.keys(S.combos)]);if(!names.has(S.context.className))S.context.className='Test';$('#classSelector').innerHTML=[...names].sort().map(n=>`<option ${n===S.context.className?'selected':''}>${esc(n)}</option>`).join('');$('#specSelector').value=S.context.spec;ensure()}
function home(){const t=trs();$('#overviewMetrics').innerHTML=metric('Skills',skills().length)+metric('Transitions',t.length)+metric('Approved timings',t.filter(x=>['validated','corrected'].includes(st(x))).length)+metric('Class combos',combos().length)+metric('Current combo',seq().length);$('#overviewFocus').textContent=`${S.context.className} · ${S.context.spec} · ${String(S.prefs.combatMode).toUpperCase()} · ${S.prefs.profile} profile`}
function skillSummary(s){const parts=[];if(s.protection)parts.push(s.protection);if(num(s.cooldown))parts.push(`CD ${num(s.cooldown)}s`);if(num(s.staminaCost))parts.push(`STA ${num(s.staminaCost)}`);if(num(s.resourceCost))parts.push(`RES ${num(s.resourceCost)}`);return parts.join(' · ')||'No protection/resource data'}
function skillsR(){const h=$('#skillsTable'),d=skills();h.innerHTML=d.length?'<div class="rows">'+d.map((s,i)=>`<article class="row"><div class="row-title"><strong>${esc(s.name||'Unnamed')}</strong><small>${esc(s.phase||'unclassified')} · ${esc(arr(s.cc).join(', ')||'No CC')}</small><small>${esc(skillSummary(s))}</small></div><div class="cell"><span>PvE / PvP</span><b>${num(s.pveDamage)||'—'} / ${num(s.pvpDamage)||'—'}</b></div><div class="cell"><span>Duration / Hit</span><b>${num(s.duration)?num(s.duration).toFixed(3)+'s':'—'} / ${s.damageAt!=null?num(s.damageAt).toFixed(3)+'s':'—'}</b></div><div class="cell"><span>CC timing</span><b>${arr(s.cc).length?(s.ccAt!=null?num(s.ccAt).toFixed(3)+'s':'unknown'):'No CC'}</b></div><div class="actions"><button data-add="${i}">Add to combo</button><button data-edit-skill="${i}">Edit</button><button data-del="${i}" class="danger">Delete</button></div></article>`).join('')+'</div>':'<div class="empty">No skills registered.</div>'}
function trR(){const d=trs(),h=$('#transitionList');$('#transitionSummary').innerHTML=metric('Entries',d.length)+metric('Approved',d.filter(x=>['validated','corrected'].includes(st(x))).length)+metric('Pending',d.filter(x=>st(x)==='pending').length)+metric('Rejected',d.filter(x=>st(x)==='rejected').length)+metric('Active',d.filter(x=>x.enabled!==false).length);h.innerHTML=d.length?d.map((t,i)=>`<article class="row"><div class="row-title"><strong>${esc(t.from||t.fromSkill||'?')} → ${esc(t.to||t.toSkill||'?')}</strong><small>${esc(t.kind||'transition')} · confidence ${t.confidence!=null?Math.round(num(t.confidence)*100)+'%':'—'}${t.fps?` · ${num(t.fps)} FPS`:''}</small></div><div class="cell"><span>Transition</span><b>${t.timingSeconds!=null?num(t.timingSeconds).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Cancel point</span><b>${t.cancelAt!=null?num(t.cancelAt).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Entry skip</span><b>${t.entryOffset!=null?num(t.entryOffset).toFixed(4)+' s':'—'}</b></div><div class="actions"><span class="status-pill ${st(t)==='rejected'?'bad':st(t)==='pending'?'warn':'good'}">${st(t)}</span><button data-v="${i}">Validate</button><button data-correct="${i}">Correct</button><button data-r="${i}" class="danger">Reject</button></div></article>`).join(''):'<div class="empty">No transitions or cancels registered.</div>'}
function comboR(){const h=$('#classCombosList'),d=combos();h.innerHTML=d.length?d.map((c,i)=>`<article class="row"><div class="row-title"><strong>${esc(c.name||'Combo')}</strong><small>${esc(c.orientation||'Mixed')}</small></div><div class="cell" style="grid-column:span 3"><span>Sequence</span><b>${esc(arr(c.sequence).join(' → '))}</b></div><div class="actions"><button data-load="${i}">Load</button></div></article>`).join(''):'<div class="empty">No class combos registered.</div>'}
function addonR(){$('#addonList').innerHTML=addons().length?addons().map(a=>`<article class="row"><div class="row-title"><strong>${esc(a.skill||'Skill')}</strong><small>${esc(a.label||'Add-on')}</small></div><div class="cell" style="grid-column:span 3"><span>Effect</span><b>${esc(a.effect||'—')}</b></div></article>`).join(''):'<div class="empty">No skill add-ons registered.</div>'}
function builder(){const q=seq(),ss=q.map(n=>skills().find(s=>String(s.name).toLowerCase()===String(n).toLowerCase())).filter(Boolean),d=ss.reduce((a,s)=>a+num(S.prefs.combatMode==='pve'?s.pveDamage:s.pvpDamage),0),dur=ss.reduce((a,s)=>a+num(s.duration),0);$('#builderStats').innerHTML=[['Skills',q.length],['Damage',d],['Duration',dur.toFixed(2)+' s'],['Estimated DPS',dur?Math.round(d/dur):0],['CC effects',ss.reduce((a,s)=>a+arr(s.cc).length,0)],['Protection',ss.filter(s=>s.protection).length]].map(x=>`<div class="stat-cell"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#comboSequence').innerHTML=q.length?q.map((n,i)=>`<span class="skill-chip">${i+1}. ${esc(n)}<button data-x="${i}">×</button></span>`).join(''):'<span class="empty" style="width:100%">Add skills to build a combo.</span>';$('#suggestions').innerHTML='<div class="empty">AnalysisCore connection will be re-enabled after the clean runtime is stable.</div>';$('#coach').innerHTML=`<div class="coach-item"><strong>${String(S.prefs.combatMode).toUpperCase()} · ${esc(S.prefs.profile)}</strong><p>Coach uses the active combat settings.</p></div>`}
const presets={balanced:{profile:'balanced',combatMode:'pvp',damageFocus:'balanced',ccFocus:'high',protectionPriority:'medium',timingTolerance:'normal',resourceDiscipline:'balanced'},'pvp-safe':{profile:'safe',combatMode:'pvp',damageFocus:'balanced',ccFocus:'high',protectionPriority:'strict',protectionGaps:'strict',timingTolerance:'tight',transitionPolicy:'validated',cancelPolicy:'validated',resourceDiscipline:'strict'},'pvp-burst':{profile:'aggressive',combatMode:'pvp',damageFocus:'high',ccFocus:'high',protectionPriority:'medium',timingTolerance:'tight',resourceDiscipline:'balanced'},'pve-dps':{profile:'dps',combatMode:'pve',damageFocus:'maximum',ccFocus:'low',protectionPriority:'low',timingTolerance:'normal',resourceDiscipline:'balanced',strictCC:false}};
const groups=[
['Mode & search',[['combatMode','Combat mode',['pvp','pve']],['profile','Analysis profile',['balanced','safe','aggressive','dps']],['searchDepth','Search depth',['fast','standard','deep']],['maxComboSkills','Maximum combo skills','number']]],
['Damage & CC',[['damageFocus','Damage focus',['low','balanced','high','maximum']],['specialAttackFocus','Special attack focus',['low','balanced','high']],['cooldownTolerance','Cooldown tolerance',['low','medium','high']],['ccFocus','CC focus',['low','medium','high']],['strictCC','Strict CC','boolean'],['smashUsage','Smash usage',['never','situational','prefer']],['wastedCC','Wasted CC',['allow','avoid','strict']]]],
['Protection & timing',[['protectionPriority','Protection priority',['low','medium','strict']],['protectionGaps','Protection gaps',['allow','avoid','strict']],['timingTolerance','Timing tolerance',['loose','normal','tight']],['transitionPolicy','Transition policy',['all','measured','validated']],['cancelPolicy','Cancel policy',['all','measured','validated']]]],
['Resources & confidence',[['resourceDiscipline','Resource discipline',['relaxed','balanced','strict']],['staminaReserve','Stamina reserve',['low','medium','high']],['resourceReserve','Resource reserve',['low','medium','high']],['confidence','Minimum confidence',['low','medium','high']],['missingData','Missing data',['permissive','cautious','strict']],['adviceStyle','Coach style',['concise','detailed','technical']]]]
];
function ctl(k,type){const v=S.prefs[k];if(type==='boolean')return `<input data-set="${k}" type="checkbox" ${v?'checked':''}>`;if(type==='number')return `<input data-set="${k}" type="number" min="1" max="30" value="${num(v,10)}">`;return `<select data-set="${k}">${type.map(x=>`<option value="${x}" ${x===v?'selected':''}>${x}</option>`).join('')}</select>`}
function settings(){const h=$('#settingsForm');h.innerHTML=groups.map(([title,rows])=>`<section class="setting-group"><h2>${title}</h2>${rows.map(([k,label,type])=>`<label class="setting-row"><span>${label}</span>${ctl(k,type)}</label>`).join('')}</section>`).join('');$$('#presetBar button').forEach(b=>b.classList.toggle('active',b.dataset.preset===S.prefs.activePreset))}
function render(p){({home,skills:skillsR,classCombos:comboR,transitions:trR,video:()=>{$('#videoMarkers').innerHTML='<div class="empty">Video markers ready.</div>'},addons:addonR,builder,settings}[p]||(()=>{}))()}
function dialog(title,fields,onSave){const d=$('#editorDialog'),box=$('#editorFields'),form=$('#editorForm');$('#editorTitle').textContent=title;box.innerHTML=fields.map(f=>`<label class="${f.wide?'wide':''}">${esc(f.label)}${f.type==='textarea'?`<textarea name="${f.name}">${esc(f.value??'')}</textarea>`:`<input name="${f.name}" type="${f.type||'text'}" step="any" value="${esc(f.value??'')}">`}</label>`).join('');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));onSave(fd);d.close()};d.showModal()}
function editSkill(i=null){const d=skills(),s=i==null?{}:d[i];dialog(i==null?'Add skill':'Edit skill',[
{name:'name',label:'Name',value:s.name},{name:'phase',label:'Combat phase',value:s.phase},{name:'pveDamage',label:'PvE damage',type:'number',value:s.pveDamage},{name:'pvpDamage',label:'PvP damage',type:'number',value:s.pvpDamage},{name:'duration',label:'Animation duration (s)',type:'number',value:s.duration},{name:'cooldown',label:'Cooldown (s)',type:'number',value:s.cooldown},{name:'damageAt',label:'Main damage at (s)',type:'number',value:s.damageAt},{name:'cc',label:'CC types, comma separated',value:arr(s.cc).join(', ')},{name:'ccAt',label:'CC applies at (s)',type:'number',value:s.ccAt},{name:'protection',label:'Protection',value:s.protection},{name:'staminaCost',label:'Stamina cost',type:'number',value:s.staminaCost},{name:'resourceCost',label:'Resource cost',type:'number',value:s.resourceCost},{name:'mobility',label:'Mobility / movement',value:s.mobility},{name:'specialAttacks',label:'Special attacks, comma separated',value:arr(s.specialAttacks).join(', ')},{name:'buffs',label:'Buffs, comma separated',wide:true,value:arr(s.buffs).join(', ')},{name:'debuffs',label:'Debuffs, comma separated',wide:true,value:arr(s.debuffs).join(', ')},{name:'notes',label:'Notes',type:'textarea',wide:true,value:s.notes}
],fd=>{const x={...s,...fd,pveDamage:num(fd.pveDamage),pvpDamage:num(fd.pvpDamage),duration:num(fd.duration),cooldown:num(fd.cooldown),damageAt:fd.damageAt===''?null:num(fd.damageAt),cc:arr(fd.cc),ccAt:fd.ccAt===''?null:num(fd.ccAt),staminaCost:num(fd.staminaCost),resourceCost:num(fd.resourceCost),specialAttacks:arr(fd.specialAttacks),buffs:arr(fd.buffs),debuffs:arr(fd.debuffs),enabled:true};i==null?d.push(x):d[i]=x;save();skillsR();home()})}
function editTr(i=null,correct=false){const d=trs(),t=i==null?{}:d[i];dialog(i==null?'Add transition':correct?'Correct transition':'Edit transition',[
{name:'from',label:'From skill',value:t.from||t.fromSkill},{name:'to',label:'To skill',value:t.to||t.toSkill},{name:'kind',label:'Transition type',value:t.kind||t.transitionType||'transition'},{name:'timingSeconds',label:'Transition duration (s)',type:'number',value:t.timingSeconds},{name:'cancelAt',label:'Cancel point in source (s)',type:'number',value:t.cancelAt},{name:'entryOffset',label:'Entry skip in target (s)',type:'number',value:t.entryOffset},{name:'confidence',label:'Confidence 0-1',type:'number',value:t.confidence},{name:'fps',label:'Measured FPS',type:'number',value:t.fps},{name:'frames',label:'Measured frames',type:'number',value:t.frames},{name:'condition',label:'Condition / input requirement',wide:true,value:t.condition},{name:'protection',label:'Protection during transition',wide:true,value:t.protection},{name:'notes',label:'Notes',type:'textarea',wide:true,value:t.notes}
],fd=>{const x={...t,from:fd.from,to:fd.to,kind:fd.kind,timingSeconds:fd.timingSeconds===''?null:num(fd.timingSeconds),cancelAt:fd.cancelAt===''?null:num(fd.cancelAt),entryOffset:fd.entryOffset===''?null:num(fd.entryOffset),confidence:fd.confidence===''?null:num(fd.confidence),fps:fd.fps===''?null:num(fd.fps),frames:fd.frames===''?null:num(fd.frames),condition:fd.condition,protection:fd.protection,notes:fd.notes,enabled:true,reviewStatus:correct?'corrected':(t.reviewStatus||'pending'),needsValidation:!correct,manualValidation:!!correct,reviewedAt:new Date().toISOString()};i==null?d.push(x):d[i]=x;save();trR();home()})}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.closest('#nav'))return go(b.dataset.page);if(b.id==='addSkillBtn')return editSkill();if(b.id==='addTransitionBtn')return editTr();if(b.id==='addComboBtn'){const n=prompt('Combo name');if(n){combos().push({name:n,sequence:[]});save();comboR()}return}if(b.id==='addAddonBtn'){const n=prompt('Skill');if(n){addons().push({skill:n,label:'Add-on',effect:''});save();addonR()}return}if(b.id==='clearComboBtn'){seq().splice(0);save();return builder()}if(b.dataset.add!=null&&b.closest('#skillsTable')){seq().push(skills()[+b.dataset.add].name);save();return go('builder')}if(b.dataset.editSkill!=null)return editSkill(+b.dataset.editSkill);if(b.dataset.del!=null&&b.closest('#skillsTable')){skills().splice(+b.dataset.del,1);save();return skillsR()}if(b.dataset.v!=null){const t=trs()[+b.dataset.v];t.reviewStatus='validated';t.needsValidation=false;t.enabled=true;t.manualValidation=true;t.reviewedAt=new Date().toISOString();save();return trR()}if(b.dataset.correct!=null)return editTr(+b.dataset.correct,true);if(b.dataset.r!=null){const t=trs()[+b.dataset.r];t.reviewStatus='rejected';t.needsValidation=false;t.enabled=false;t.reviewedAt=new Date().toISOString();save();return trR()}if(b.dataset.load!=null){const c=combos()[+b.dataset.load];seq().splice(0,seq().length,...arr(c.sequence));save();return go('builder')}if(b.dataset.x!=null){seq().splice(+b.dataset.x,1);save();return builder()}if(b.dataset.preset){Object.assign(S.prefs,presets[b.dataset.preset]||{});S.prefs.activePreset=b.dataset.preset;save();settings();builder();}});$('#classSelector').addEventListener('change',e=>{S.context.className=e.target.value;ensure();save();render(page)});$('#specSelector').addEventListener('change',e=>{S.context.spec=e.target.value;ensure();save();render(page)});$('#settingsForm').addEventListener('change',e=>{const x=e.target.closest('[data-set]');if(!x)return;S.prefs[x.dataset.set]=x.type==='checkbox'?x.checked:x.type==='number'?num(x.value):x.value;S.prefs.activePreset='';save();if(page==='settings')settings();builder()})}
function init(){try{context();bind();go('home');const h=$('#appHealth');h.textContent='Ready · V3.2';h.className='status-pill good'}catch(e){console.error(e);const h=$('#appHealth');h.textContent='Runtime error';h.className='status-pill bad';h.title=e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();