(()=>{'use strict';
const KEY='bcl.clean.v2';
const ENDPOINT='https://rxwlcwziuhtlujdmjwom.supabase.co/functions/v1/analysiscore-builder-v2';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4d2xjd3ppdWh0bHVqZG1qd29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDgwMzMsImV4cCI6MjEwMjUyNDAzM30.EIFJXVhKlIyOcfcYPmiz4ct10iTpMqe_Dk4Jal49ChU';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:(typeof v==='string'&&v.trim()?v.split(',').map(x=>x.trim()).filter(Boolean):[]);
const fresh=()=>({version:2,context:{className:'Test',spec:'Awakening'},skills:{Test:{Awakening:[{name:'Engage Step',phase:'engagement',pveDamage:420,pvpDamage:280,duration:.55,cooldown:4,cc:[],protection:'Super Armor',enabled:true},{name:'Raven Crescent',phase:'cc',pveDamage:1572,pvpDamage:1030,duration:1.1,cooldown:7,cc:['Stun'],ccAt:.72,enabled:true},{name:'Broken Torrent',phase:'burst',pveDamage:4584,pvpDamage:3025,duration:1.25,cooldown:9,cc:[],protection:'Forward Guard',enabled:true},{name:'Silent Bane',phase:'finish',pveDamage:3320,pvpDamage:2180,duration:1.05,cooldown:8,cc:['Bound'],ccAt:.65,enabled:true}],Succession:[]}},transitions:{Test:{Awakening:[{from:'Engage Step',to:'Raven Crescent',timingSeconds:.18,cancelAt:.42,entryOffset:.18,reviewStatus:'validated',enabled:true},{from:'Raven Crescent',to:'Broken Torrent',timingSeconds:.14,cancelAt:.86,entryOffset:.32,reviewStatus:'validated',enabled:true},{from:'Broken Torrent',to:'Silent Bane',timingSeconds:.16,cancelAt:.74,entryOffset:.12,reviewStatus:'pending',needsValidation:true,enabled:true}],Succession:[]}},combos:{Test:{Awakening:[{name:'Starter PvP route',orientation:'PvP',sequence:['Engage Step','Raven Crescent','Broken Torrent','Silent Bane']}],Succession:[]}},addons:{Test:{Awakening:[],Succession:[]}},builder:{Test:{Awakening:[],Succession:[]}},videoMarkers:[],prefs:{profile:'balanced',searchDepth:'standard',maxComboSkills:10,combatMode:'pvp',strictCC:true,ccFocus:'high',damageFocus:'balanced',protectionPriority:'medium',timingTolerance:'normal',transitionPolicy:'measured',cancelPolicy:'measured',resourceDiscipline:'balanced',confidence:'medium',adviceStyle:'detailed'}});
function normalize(raw){const s=raw&&typeof raw==='object'?raw:fresh();const f=fresh();s.version=2;s.context={...f.context,...(s.context||{})};for(const k of ['skills','transitions','combos','addons','builder'])if(!s[k]||typeof s[k]!=='object')s[k]={};if(!Array.isArray(s.videoMarkers))s.videoMarkers=[];s.prefs={...f.prefs,...(s.prefs||{})};return s}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)return normalize(x)}catch(_){}const s=fresh();try{const old=JSON.parse(localStorage.getItem('bcl.clean.v1')||'null');if(old)Object.assign(s,old)}catch(_){}try{const sk=JSON.parse(localStorage.getItem('bdoCombosLabs.imported.skills')||'null'),tr=JSON.parse(localStorage.getItem('bdoCombosLabs.imported.transitions')||'null'),cb=JSON.parse(localStorage.getItem('bdoCombosLabs.imported.combos')||'null');if(sk)s.skills=sk;if(tr)s.transitions=tr;if(cb)s.combos=cb}catch(_){}return normalize(s)}
let state=load(),page='home',suggestions=[],coach=[];
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){runtimeError(e)}}
function ensure(cls=state.context.className,spec=state.context.spec){for(const k of ['skills','transitions','combos','addons','builder']){state[k]??={};state[k][cls]??={Awakening:[],Succession:[]};if(!Array.isArray(state[k][cls][spec]))state[k][cls][spec]=[]}}
const list=k=>{ensure();return state[k][state.context.className][state.context.spec].filter(Boolean)};
const skills=()=>list('skills'),transitions=()=>list('transitions'),combos=()=>list('combos'),addons=()=>list('addons'),sequence=()=>{ensure();return state.builder[state.context.className][state.context.spec]};
function runtimeError(e){console.error('[BCL V2]',e);const h=$('#appHealth');if(h){h.textContent='Runtime error';h.className='status-pill bad';h.title=e?.message||String(e)}}
window.addEventListener('error',e=>runtimeError(e.error||new Error(e.message)));window.addEventListener('unhandledrejection',e=>runtimeError(e.reason||new Error('Promise rejected')));
function metric(a,b){return `<div class="metric"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`}
function go(p){page=p;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));render(p)}
function renderContext(){const names=new Set(['Test',...Object.keys(state.skills||{}),...Object.keys(state.transitions||{}),...Object.keys(state.combos||{})]);if(!names.has(state.context.className))state.context.className=[...names][0];const c=$('#classSelector');if(c)c.innerHTML=[...names].sort().map(n=>`<option value="${esc(n)}" ${n===state.context.className?'selected':''}>${esc(n)}</option>`).join('');const s=$('#specSelector');if(s)s.value=state.context.spec;ensure()}
function renderHome(){const t=transitions();$('#overviewMetrics').innerHTML=metric('Skills',skills().length)+metric('Transitions',t.length)+metric('Approved timings',t.filter(x=>['validated','corrected'].includes(status(x))).length)+metric('Class combos',combos().length)+metric('Current combo',sequence().length);$('#overviewFocus').textContent=`${state.context.className} · ${state.context.spec} · ${String(state.prefs.combatMode).toUpperCase()} · ${state.prefs.profile} profile`}
function renderSkills(){const h=$('#skillsTable'),d=skills();if(!d.length){h.innerHTML='<div class="empty">No skills registered.</div>';return}h.innerHTML='<div class="rows">'+d.map((s,i)=>`<article class="row"><div class="row-title"><strong>${esc(s.name||'Unnamed')}</strong><small>${esc(s.phase||'unclassified')} · ${esc(arr(s.cc).join(', ')||'No CC')}</small></div><div class="cell"><span>PvE damage</span><b>${num(s.pveDamage??s.damage)||'—'}</b></div><div class="cell"><span>PvP damage</span><b>${num(s.pvpDamage)||'—'}</b></div><div class="cell"><span>Duration</span><b>${num(s.duration)?num(s.duration).toFixed(3)+' s':'—'}</b></div><div class="actions"><button data-add="${i}">Add to combo</button><button data-edit="${i}">Edit</button><button class="danger" data-del="${i}">Delete</button></div></article>`).join('')+'</div>';h.onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.add??b.dataset.edit??b.dataset.del);if('add'in b.dataset){sequence().push(d[i].name);save();go('builder')}else if('edit'in b.dataset)editSkill(i);else if('del'in b.dataset){d.splice(i,1);save();renderSkills()}}}
function renderCombos(){const h=$('#classCombosList'),d=combos();if(!d.length){h.innerHTML='<div class="empty">No class combos registered.</div>';return}h.innerHTML=d.map((c,i)=>`<article class="row"><div class="row-title"><strong>${esc(c.name||'Combo')}</strong><small>${esc(c.orientation||'Mixed')}</small></div><div class="cell" style="grid-column:span 3"><span>Sequence</span><b>${esc(arr(c.sequence).join(' → '))}</b></div><div class="actions"><button data-load="${i}">Load</button><button data-edit="${i}">Edit</button><button class="danger" data-del="${i}">Delete</button></div></article>`).join('');h.onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.load??b.dataset.edit??b.dataset.del);if('load'in b.dataset){const q=sequence();q.splice(0,q.length,...arr(d[i].sequence));save();go('builder')}else if('edit'in b.dataset)editCombo(i);else if('del'in b.dataset){d.splice(i,1);save();renderCombos()}}}
function status(t){const s=String(t.reviewStatus||'').toLowerCase();return ['validated','corrected','rejected'].includes(s)?s:(t.needsValidation?'pending':'manual')}
function renderTransitions(){const d=transitions(),sum=$('#transitionSummary'),h=$('#transitionList');sum.innerHTML=metric('Entries',d.length)+metric('Approved',d.filter(x=>['validated','corrected'].includes(status(x))).length)+metric('Pending',d.filter(x=>status(x)==='pending').length)+metric('Rejected',d.filter(x=>status(x)==='rejected').length)+metric('Active',d.filter(x=>x.enabled!==false).length);if(!d.length){h.innerHTML='<div class="empty">No transitions or cancels registered.</div>';return}h.innerHTML=d.map((t,i)=>{const s=status(t);return `<article class="row"><div class="row-title"><strong>${esc(t.from||t.fromSkill||'?')} → ${esc(t.to||t.toSkill||'?')}</strong><small>${esc(t.kind||t.transitionType||'transition')}</small></div><div class="cell"><span>Transition</span><b>${t.timingSeconds!=null?num(t.timingSeconds).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Cancel point</span><b>${t.cancelAt!=null?num(t.cancelAt).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Entry skip</span><b>${t.entryOffset!=null?num(t.entryOffset).toFixed(4)+' s':'—'}</b></div><div class="actions"><span class="status-pill ${s==='rejected'?'bad':s==='pending'?'warn':['validated','corrected'].includes(s)?'good':''}">${esc(s)}</span><button data-v="${i}">Validate</button><button data-c="${i}">Correct</button><button class="danger" data-r="${i}">Reject</button></div></article>`}).join('');h.onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.v??b.dataset.c??b.dataset.r);if('v'in b.dataset)review(i,'validated');else if('r'in b.dataset)review(i,'rejected');else if('c'in b.dataset)editTransition(i,true)}}
function review(i,s){const t=transitions()[i];if(!t)return;t.reviewStatus=s;t.needsValidation=false;t.manualValidation=s==='validated';t.enabled=s!=='rejected';t.reviewedAt=new Date().toISOString();save();renderTransitions()}
function renderVideo(){const h=$('#videoMarkers'),d=state.videoMarkers;if(!d.length){h.innerHTML='<div class="empty">No timing markers yet.</div>';return}h.innerHTML=d.map((x,i)=>`<article class="row"><div class="row-title"><strong>${esc(x.type)}</strong><small>Frame ${x.frame} @ ${x.fps} FPS</small></div><div class="cell"><span>Timestamp</span><b>${num(x.time).toFixed(4)} s</b></div><div class="cell" style="grid-column:span 2"><span>Use</span><b>Attach this event to a skill or transition.</b></div><div class="actions"><button class="danger" data-del="${i}">Delete</button></div></article>`).join('');h.onclick=e=>{const b=e.target.closest('[data-del]');if(!b)return;d.splice(Number(b.dataset.del),1);save();renderVideo()}}
function renderAddons(){const h=$('#addonList'),d=addons();if(!d.length){h.innerHTML='<div class="empty">No skill add-ons registered.</div>';return}h.innerHTML=d.map((a,i)=>`<article class="row"><div class="row-title"><strong>${esc(a.skill||'Skill')}</strong><small>${esc(a.label||'Add-on')}</small></div><div class="cell" style="grid-column:span 3"><span>Effect</span><b>${esc(a.effect||'—')}</b></div><div class="actions"><button data-edit="${i}">Edit</button><button class="danger" data-del="${i}">Delete</button></div></article>`).join('');h.onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.edit??b.dataset.del);if('edit'in b.dataset)editAddon(i);else if('del'in b.dataset){d.splice(i,1);save();renderAddons()}}}
function findSkill(n){return skills().find(s=>String(s.name).toLowerCase()===String(n).toLowerCase())}
function renderBuilder(){const q=sequence(),ss=q.map(findSkill).filter(Boolean),damage=ss.reduce((a,s)=>a+num(state.prefs.combatMode==='pve'?(s.pveDamage??s.damage):s.pvpDamage),0),duration=ss.reduce((a,s)=>a+Math.max(.01,num(s.duration,.5)),0);$('#builderStats').innerHTML=[['Skills',q.length],['Damage',Math.round(damage)],['Duration',duration.toFixed(3)+' s'],['Estimated DPS',duration?Math.round(damage/duration):0],['CC effects',ss.reduce((a,s)=>a+arr(s.cc).length,0)],['Protection',ss.length?Math.round(ss.filter(s=>s.protection).length/ss.length*100)+'%':'0%']].map(x=>`<div class="stat-cell"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');const h=$('#comboSequence');h.innerHTML=q.length?q.map((n,i)=>`<span class="skill-chip">${i+1}. ${esc(n)}<button data-x="${i}">×</button></span>`).join(''):'<span class="empty" style="width:100%">Add skills or let AnalysisCore build a route.</span>';h.onclick=e=>{const b=e.target.closest('[data-x]');if(!b)return;q.splice(Number(b.dataset.x),1);save();renderBuilder()};renderSuggestions();renderCoach()}
function renderSuggestions(){const h=$('#suggestions');if(!suggestions.length){h.innerHTML='<div class="empty">Run AnalysisCore to get suggestions.</div>';return}h.innerHTML=suggestions.map((s,i)=>`<article class="row" style="grid-template-columns:1fr 110px 130px"><div class="row-title"><strong>${i+1}. ${esc(s.skill||s.name||'Skill')}</strong><small>${esc(s.phase||'')} · score ${Number.isFinite(Number(s.score))?Number(s.score).toFixed(3):'—'}</small></div><div class="cell"><span>Damage</span><b>${Math.round(num(s.metrics?.damage))||'—'}</b></div><div class="actions"><button data-add="${i}">Add</button></div></article>`).join('');h.onclick=e=>{const b=e.target.closest('[data-add]');if(!b)return;const s=suggestions[Number(b.dataset.add)];if(s?.skill){sequence().push(s.skill);save();renderBuilder()}}}
function renderCoach(){const h=$('#coach');if(!coach.length){h.innerHTML=`<div class="coach-item"><strong>${String(state.prefs.combatMode).toUpperCase()} · ${esc(state.prefs.profile)}</strong><p>Coach uses the active settings: damage ${esc(state.prefs.damageFocus)}, protection ${esc(state.prefs.protectionPriority)}, timing ${esc(state.prefs.timingTolerance)}, CC ${state.prefs.strictCC?'strict':'flexible'}.</p></div>`;return}h.innerHTML=coach.map(x=>`<div class="coach-item"><strong>${esc(x.title||x.kind||'Advice')}</strong><p>${esc(x.text||x.message||String(x))}</p></div>`).join('')}
async function analysis(action){const st=$('#analysisStatus');st.textContent='AnalysisCore running…';st.className='status-pill warn';try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':ANON,'authorization':'Bearer '+ANON},body:JSON.stringify({action,skills:skills().filter(x=>x.enabled!==false),transitions:transitions().filter(x=>x.enabled!==false),prefix:[...sequence()],preferences:state.prefs,limit:8})});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${r.status}`);suggestions=Array.isArray(d.suggestions)?d.suggestions:[];coach=Array.isArray(d.coach)?d.coach:(Array.isArray(d.advice)?d.advice:[]);if(action==='complete'){const best=(d.results||[]).find(x=>Array.isArray(x.sequence));if(best){const q=sequence();q.splice(0,q.length,...best.sequence);save()}}st.textContent=`AnalysisCore · ${String(state.prefs.combatMode).toUpperCase()} · ${state.prefs.profile}`;st.className='status-pill good';renderBuilder()}catch(e){st.textContent='AnalysisCore: '+e.message;st.className='status-pill bad';runtimeError(e)}}
const presets={balanced:{profile:'balanced',combatMode:'pvp',strictCC:true,damageFocus:'balanced',ccFocus:'high',protectionPriority:'medium',timingTolerance:'normal'},'pvp-safe':{profile:'safe',combatMode:'pvp',strictCC:true,damageFocus:'balanced',ccFocus:'high',protectionPriority:'strict',timingTolerance:'tight'},'pvp-burst':{profile:'aggressive',combatMode:'pvp',strictCC:true,damageFocus:'high',ccFocus:'high',protectionPriority:'medium',timingTolerance:'tight'},'pve-dps':{profile:'dps',combatMode:'pve',strictCC:false,damageFocus:'maximum',ccFocus:'low',protectionPriority:'low',timingTolerance:'normal'}};
function applyPreset(n){Object.assign(state.prefs,presets[n]||{});save();$$('#presetBar button').forEach(b=>b.classList.toggle('active',b.dataset.preset===n));renderSettings();renderBuilder()}
const groups=[['Mode & search',[['combatMode','Combat mode',['pvp','pve']],['profile','Analysis profile',['balanced','safe','aggressive','dps']],['searchDepth','Search depth',['fast','standard','deep']],['maxComboSkills','Maximum combo skills','number']]],['Combat priorities',[['damageFocus','Damage focus',['low','balanced','high','maximum']],['ccFocus','CC focus',['low','medium','high']],['protectionPriority','Protection priority',['low','medium','strict']],['strictCC','Strict CC','boolean']]],['Timing & transitions',[['timingTolerance','Timing tolerance',['loose','normal','tight']],['transitionPolicy','Transition policy',['all','measured','validated']],['cancelPolicy','Cancel policy',['all','measured','validated']]],['Resources & coach',[['resourceDiscipline','Resource discipline',['relaxed','balanced','strict']],['confidence','Minimum confidence',['low','medium','high']],['adviceStyle','Coach style',['concise','detailed','technical']]]];
function control(k,t){const v=state.prefs[k];if(t==='boolean')return `<input data-setting="${k}" type="checkbox" ${v?'checked':''}>`;if(t==='number')return `<input data-setting="${k}" type="number" min="1" max="30" value="${num(v,10)}">`;return `<select data-setting="${k}">${t.map(x=>`<option value="${x}" ${x===v?'selected':''}>${x}</option>`).join('')}</select>`}
function renderSettings(){const h=$('#settingsForm');h.innerHTML=groups.map(([title,rows])=>`<section class="setting-group"><h2>${title}</h2>${rows.map(([k,l,t])=>`<label class="setting-row"><span>${l}</span>${control(k,t)}</label>`).join('')}</section>`).join('');h.onchange=e=>{const el=e.target.closest('[data-setting]');if(!el)return;state.prefs[el.dataset.setting]=el.type==='checkbox'?el.checked:(el.type==='number'?num(el.value):el.value);save();renderBuilder()}}
function dialog(title,fields,done){const d=$('#editorDialog'),form=$('#editorForm'),box=$('#editorFields');$('#editorTitle').textContent=title;box.innerHTML=fields.map(f=>`<label class="${f.wide?'wide':''}">${esc(f.label)}${f.type==='textarea'?`<textarea name="${f.name}">${esc(f.value??'')}</textarea>`:`<input name="${f.name}" type="${f.type||'text'}" step="any" value="${esc(f.value??'')}">`}</label>`).join('');form.onsubmit=e=>{e.preventDefault();done(Object.fromEntries(new FormData(form)));d.close()};d.showModal()}
function editSkill(i=null){const d=skills(),s=i==null?{}:d[i];dialog(i==null?'Add skill':'Edit skill',[{name:'name',label:'Name',value:s.name},{name:'phase',label:'Combat phase',value:s.phase},{name:'pveDamage',label:'PvE damage',type:'number',value:s.pveDamage},{name:'pvpDamage',label:'PvP damage',type:'number',value:s.pvpDamage},{name:'duration',label:'Duration (s)',type:'number',value:s.duration},{name:'cooldown',label:'Cooldown (s)',type:'number',value:s.cooldown},{name:'cc',label:'CC types',value:arr(s.cc).join(', ')},{name:'ccAt',label:'CC applies at (s)',type:'number',value:s.ccAt},{name:'protection',label:'Protection',value:s.protection}],fd=>{const x={...s,...fd,pveDamage:num(fd.pveDamage),pvpDamage:num(fd.pvpDamage),duration:num(fd.duration),cooldown:num(fd.cooldown),cc:arr(fd.cc),ccAt:fd.ccAt===''?null:num(fd.ccAt),enabled:true};i==null?d.push(x):d[i]=x;save();renderSkills();renderHome()})}
function editTransition(i=null,correct=false){const d=transitions(),t=i==null?{}:d[i];dialog(i==null?'Add transition':correct?'Correct transition':'Edit transition',[{name:'from',label:'From skill',value:t.from||t.fromSkill},{name:'to',label:'To skill',value:t.to||t.toSkill},{name:'timingSeconds',label:'Transition duration (s)',type:'number',value:t.timingSeconds},{name:'cancelAt',label:'Cancel point (s)',type:'number',value:t.cancelAt},{name:'entryOffset',label:'Entry skip (s)',type:'number',value:t.entryOffset},{name:'kind',label:'Type',value:t.kind||t.transitionType||'transition'}],fd=>{const x={...t,from:fd.from,to:fd.to,timingSeconds:fd.timingSeconds===''?null:num(fd.timingSeconds),cancelAt:fd.cancelAt===''?null:num(fd.cancelAt),entryOffset:fd.entryOffset===''?null:num(fd.entryOffset),kind:fd.kind,enabled:true,reviewStatus:correct?'corrected':(t.reviewStatus||'pending'),needsValidation:!correct,manualValidation:!!correct,reviewedAt:new Date().toISOString()};i==null?d.push(x):d[i]=x;save();renderTransitions()})}
function editCombo(i=null){const d=combos(),c=i==null?{}:d[i];dialog(i==null?'Add combo':'Edit combo',[{name:'name',label:'Name',value:c.name},{name:'orientation',label:'Orientation',value:c.orientation||'PvP'},{name:'sequence',label:'Sequence, comma separated',wide:true,value:arr(c.sequence).join(', ')}],fd=>{const x={...c,name:fd.name,orientation:fd.orientation,sequence:arr(fd.sequence)};i==null?d.push(x):d[i]=x;save();renderCombos()})}
function editAddon(i=null){const d=addons(),a=i==null?{}:d[i];dialog(i==null?'Add skill add-on':'Edit skill add-on',[{name:'skill',label:'Skill',value:a.skill},{name:'label',label:'Label',value:a.label},{name:'effect',label:'Effect',wide:true,value:a.effect}],fd=>{const x={...a,...fd};i==null?d.push(x):d[i]=x;save();renderAddons()})}
function render(p){try{({home:renderHome,skills:renderSkills,classCombos:renderCombos,transitions:renderTransitions,video:renderVideo,addons:renderAddons,builder:renderBuilder,settings:renderSettings}[p]||(()=>{}))()}catch(e){runtimeError(e)}}
function init(){try{renderContext();$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#classSelector').onchange=e=>{state.context.className=e.target.value;ensure();save();renderContext();render(page)};$('#specSelector').onchange=e=>{state.context.spec=e.target.value;ensure();save();render(page)};$('#addSkillBtn').onclick=()=>editSkill();$('#addComboBtn').onclick=()=>editCombo();$('#addTransitionBtn').onclick=()=>editTransition();$('#addAddonBtn').onclick=()=>editAddon();$('#clearComboBtn').onclick=()=>{sequence().splice(0);save();renderBuilder()};$('#suggestBtn').onclick=()=>analysis('suggest');$('#completeBtn').onclick=()=>analysis('complete');$('#videoFile').onchange=e=>{const f=e.target.files?.[0];if(f)$('#timingVideo').src=URL.createObjectURL(f)};$('#markTransitionBtn').onclick=()=>mark('transition');$('#markCcBtn').onclick=()=>mark('cc');$('#markDamageBtn').onclick=()=>mark('damage');$('#clearMarkersBtn').onclick=()=>{state.videoMarkers=[];save();renderVideo()};$('#presetBar').onclick=e=>{const b=e.target.closest('[data-preset]');if(b)applyPreset(b.dataset.preset)};go('home');const h=$('#appHealth');if(h){h.textContent='Ready · V2';h.className='status-pill good'}}catch(e){runtimeError(e)}}
function mark(type){const v=$('#timingVideo'),fps=Math.max(1,num($('#videoFps').value,60)),time=num(v.currentTime);state.videoMarkers.push({type,time,frame:Math.round(time*fps),fps});save();renderVideo()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();