(()=>{'use strict';
const LS='bcl.clean.v1';
const ENDPOINT='https://rxwlcwziuhtlujdmjwom.supabase.co/functions/v1/analysiscore-builder-v2';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4d2xjd3ppdWh0bHVqZG1qd29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDgwMzMsImV4cCI6MjEwMjUyNDAzM30.EIFJXVhKlIyOcfcYPmiz4ct10iTpMqe_Dk4Jal49ChU';
const base={version:1,context:{className:'Test',spec:'Awakening'},skills:{Test:{Awakening:[
{name:'Engage Step',phase:'engagement',pveDamage:420,pvpDamage:280,duration:.55,cooldown:4,cc:[],protection:'Super Armor',staminaCost:100,resourceCost:0,enabled:true},
{name:'Raven Crescent',phase:'cc',pveDamage:1572,pvpDamage:1030,duration:1.1,cooldown:7,cc:['Stun'],ccAt:.72,protection:'',staminaCost:0,resourceCost:20,enabled:true},
{name:'Broken Torrent',phase:'burst',pveDamage:4584,pvpDamage:3025,duration:1.25,cooldown:9,cc:[],protection:'Forward Guard',staminaCost:0,resourceCost:35,enabled:true},
{name:'Silent Bane',phase:'finish',pveDamage:3320,pvpDamage:2180,duration:1.05,cooldown:8,cc:['Bound'],ccAt:.65,protection:'',staminaCost:0,resourceCost:30,enabled:true}
],Succession:[]}},transitions:{Test:{Awakening:[
{from:'Engage Step',to:'Raven Crescent',timingSeconds:.18,cancelAt:.42,entryOffset:.18,reviewStatus:'validated',enabled:true,reviewedAt:new Date().toISOString()},
{from:'Raven Crescent',to:'Broken Torrent',timingSeconds:.14,cancelAt:.86,entryOffset:.32,reviewStatus:'validated',enabled:true,reviewedAt:new Date().toISOString()},
{from:'Broken Torrent',to:'Silent Bane',timingSeconds:.16,cancelAt:.74,entryOffset:.12,reviewStatus:'pending',needsValidation:true,enabled:true}
],Succession:[]}},combos:{Test:{Awakening:[{name:'Starter PvP route',orientation:'PvP',sequence:['Engage Step','Raven Crescent','Broken Torrent','Silent Bane']}],Succession:[]}},addons:{Test:{Awakening:[],Succession:[]}},builder:{Test:{Awakening:[],Succession:[]}},videoMarkers:[],prefs:{profile:'balanced',searchDepth:'standard',maxComboSkills:10,combatMode:'pvp',strictCC:true,ccFocus:'high',damageFocus:'balanced',protectionPriority:'medium',protectionGaps:'avoid',timingTolerance:'normal',transitionPolicy:'measured',cancelPolicy:'measured',resourceDiscipline:'balanced',staminaReserve:'medium',resourceReserve:'medium',confidence:'medium',missingData:'cautious',adviceStyle:'detailed'}};
const clone=x=>JSON.parse(JSON.stringify(x));
let state=load(); let page='home'; let suggestions=[]; let coach=[];
function load(){try{const saved=JSON.parse(localStorage.getItem(LS)||'null');if(saved?.version===1)return saved}catch(_){}const s=clone(base);migrateLegacy(s);return s}
function migrateLegacy(s){try{const skills=JSON.parse(localStorage.getItem('bdoCombosLabs.imported.skills')||'null');const tr=JSON.parse(localStorage.getItem('bdoCombosLabs.imported.transitions')||'null');const cb=JSON.parse(localStorage.getItem('bdoCombosLabs.imported.combos')||'null');if(skills&&typeof skills==='object')s.skills=skills;if(tr&&typeof tr==='object')s.transitions=tr;if(cb&&typeof cb==='object')s.combos=cb}catch(_){} }
function save(){localStorage.setItem(LS,JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ensure(cls,spec){for(const key of ['skills','transitions','combos','addons','builder']){state[key][cls]??={Awakening:[],Succession:[]};state[key][cls][spec]??=[]}}
function ctx(){return state.context} function skills(){const c=ctx();ensure(c.className,c.spec);return state.skills[c.className][c.spec].filter(Boolean)} function transitions(){const c=ctx();ensure(c.className,c.spec);return state.transitions[c.className][c.spec].filter(Boolean)} function combos(){const c=ctx();ensure(c.className,c.spec);return state.combos[c.className][c.spec].filter(Boolean)} function addons(){const c=ctx();ensure(c.className,c.spec);return state.addons[c.className][c.spec].filter(Boolean)} function sequence(){const c=ctx();ensure(c.className,c.spec);return state.builder[c.className][c.spec]}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d} function arr(v){return Array.isArray(v)?v:typeof v==='string'&&v.trim()?v.split(',').map(x=>x.trim()).filter(Boolean):[]}
function init(){bindNav();bindContext();bindActions();renderAll();}
function bindNav(){$$('#nav button').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;$$('#nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+page)?.classList.add('active');renderPage(page)}))}
function bindContext(){const classSel=$('#classSelector'),specSel=$('#specSelector');classSel.addEventListener('change',()=>{state.context.className=classSel.value;ensure(classSel.value,state.context.spec);save();renderAll()});specSel.addEventListener('change',()=>{state.context.spec=specSel.value;ensure(state.context.className,specSel.value);save();renderAll()})}
function bindActions(){
 $('#addSkillBtn').onclick=()=>editSkill();$('#addComboBtn').onclick=()=>editCombo();$('#addTransitionBtn').onclick=()=>editTransition();$('#addAddonBtn').onclick=()=>editAddon();
 $('#clearComboBtn').onclick=()=>{sequence().splice(0);save();renderBuilder()};$('#suggestBtn').onclick=()=>analysis('suggest');$('#completeBtn').onclick=()=>analysis('complete');
 $('#videoFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)$('#timingVideo').src=URL.createObjectURL(f)});$('#markTransitionBtn').onclick=()=>markVideo('transition');$('#markCcBtn').onclick=()=>markVideo('cc');$('#markDamageBtn').onclick=()=>markVideo('damage');$('#clearMarkersBtn').onclick=()=>{state.videoMarkers=[];save();renderVideo()};
 $('#presetBar').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(!b)return;applyPreset(b.dataset.preset)});
}
function renderAll(){renderContext();renderPage(page);}
function renderContext(){const classes=new Set([...Object.keys(state.skills),...Object.keys(state.transitions),...Object.keys(state.combos)]);if(!classes.size)classes.add('Test');const sel=$('#classSelector');sel.innerHTML=[...classes].sort().map(x=>`<option ${x===state.context.className?'selected':''}>${esc(x)}</option>`).join('');$('#specSelector').value=state.context.spec;ensure(state.context.className,state.context.spec)}
function renderPage(p){({home:renderHome,skills:renderSkills,classCombos:renderCombos,transitions:renderTransitions,video:renderVideo,addons:renderAddons,builder:renderBuilder,settings:renderSettings}[p]||(()=>{}))()}
function metric(label,value){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function renderHome(){const sk=skills(),tr=transitions(),cb=combos(),sq=sequence(),valid=tr.filter(t=>['validated','corrected'].includes(String(t.reviewStatus))).length;$('#overviewMetrics').innerHTML=metric('Skills',sk.length)+metric('Transitions',tr.length)+metric('Approved timings',valid)+metric('Class combos',cb.length)+metric('Current combo',sq.length);$('#overviewFocus').textContent=`${ctx().className} · ${ctx().spec} · ${String(state.prefs.combatMode).toUpperCase()} · ${state.prefs.profile} profile`}
function skillDamage(s){return state.prefs.combatMode==='pve'?num(s.pveDamage??s.damage):num(s.pvpDamage)}
function renderSkills(){const host=$('#skillsTable'),data=skills();if(!data.length)return host.innerHTML='<div class="empty">No skills for this class and specialization.</div>';host.innerHTML='<div class="rows">'+data.map((s,i)=>`<article class="row"><div class="row-title"><strong>${esc(s.name||'Unnamed')}</strong><small>${esc(s.phase||'unclassified')} · ${esc(arr(s.cc).join(', ')||'No CC')}</small></div><div class="cell"><span>PvE damage</span><b>${num(s.pveDamage??s.damage)||'—'}</b></div><div class="cell"><span>PvP damage</span><b>${num(s.pvpDamage)||'—'}</b></div><div class="cell"><span>Duration</span><b>${num(s.duration)?num(s.duration).toFixed(3)+' s':'—'}</b></div><div class="actions"><button data-add="${i}">Add to combo</button><button data-edit="${i}">Edit</button><button class="danger" data-del="${i}">Delete</button></div></article>`).join('')+'</div>';host.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{sequence().push(data[+b.dataset.add].name);save();renderBuilder()});host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editSkill(+b.dataset.edit));host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{data.splice(+b.dataset.del,1);save();renderSkills()})}
function renderCombos(){const host=$('#classCombosList'),data=combos();if(!data.length)return host.innerHTML='<div class="empty">No class combos registered.</div>';host.innerHTML=data.map((c,i)=>`<article class="row"><div class="row-title"><strong>${esc(c.name||'Combo')}</strong><small>${esc(c.orientation||'Mixed')}</small></div><div class="cell" style="grid-column:span 3"><span>Sequence</span><b>${esc(arr(c.sequence).join(' → '))}</b></div><div class="actions"><button data-load="${i}">Load</button><button data-edit="${i}">Edit</button><button class="danger" data-del="${i}">Delete</button></div></article>`).join('');host.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const q=sequence();q.splice(0,q.length,...arr(data[+b.dataset.load].sequence));save();page='builder';$('#nav [data-page="builder"]').click()});host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editCombo(+b.dataset.edit));host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{data.splice(+b.dataset.del,1);save();renderCombos()})}
function trStatus(t){const s=String(t.reviewStatus||'').toLowerCase();if(['validated','corrected','rejected'].includes(s))return s;if(t.needsValidation)return'pending';return'manual'}
function renderTransitions(){const data=transitions(),sum=$('#transitionSummary'),host=$('#transitionList');const approved=data.filter(t=>['validated','corrected'].includes(trStatus(t))).length,pending=data.filter(t=>trStatus(t)==='pending').length,rejected=data.filter(t=>trStatus(t)==='rejected').length;sum.innerHTML=metric('Entries',data.length)+metric('Approved',approved)+metric('Pending',pending)+metric('Rejected',rejected)+metric('Active',data.filter(t=>t.enabled!==false).length);if(!data.length)return host.innerHTML='<div class="empty">No transitions or cancels registered.</div>';host.innerHTML=data.map((t,i)=>{const s=trStatus(t);return `<article class="row"><div class="row-title"><strong>${esc(t.from||t.fromSkill||'?')} → ${esc(t.to||t.toSkill||'?')}</strong><small>${esc(t.kind||t.transitionType||'transition')}</small></div><div class="cell"><span>Transition</span><b>${num(t.timingSeconds)?num(t.timingSeconds).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Cancel point</span><b>${t.cancelAt!=null?num(t.cancelAt).toFixed(4)+' s':'—'}</b></div><div class="cell"><span>Entry skip</span><b>${t.entryOffset!=null?num(t.entryOffset).toFixed(4)+' s':'—'}</b></div><div class="actions"><span class="status-pill ${s==='rejected'?'bad':s==='pending'?'warn':s==='validated'||s==='corrected'?'good':''}">${esc(s)}</span><button data-v="${i}">Validate</button><button data-c="${i}">Correct</button><button data-r="${i}" class="danger">Reject</button></div></article>`}).join('');host.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>reviewTr(+b.dataset.v,'validated'));host.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>reviewTr(+b.dataset.r,'rejected'));host.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>editTransition(+b.dataset.c,true))}
function reviewTr(i,status){const t=transitions()[i];if(!t)return;t.reviewStatus=status;t.needsValidation=false;t.manualValidation=status==='validated';t.enabled=status!=='rejected';t.reviewedAt=new Date().toISOString();save();renderTransitions()}
function renderVideo(){const host=$('#videoMarkers'),m=state.videoMarkers;if(!m.length)return host.innerHTML='<div class="empty">No timing markers yet.</div>';host.innerHTML=m.map((x,i)=>`<article class="row"><div class="row-title"><strong>${esc(x.type)}</strong><small>Frame ${x.frame} @ ${x.fps} FPS</small></div><div class="cell"><span>Timestamp</span><b>${x.time.toFixed(4)} s</b></div><div class="cell" style="grid-column:span 2"><span>Use</span><b>Attach this event time to a skill or transition.</b></div><div class="actions"><button class="danger" data-del="${i}">Delete</button></div></article>`).join('');host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{m.splice(+b.dataset.del,1);save();renderVideo()})}
function markVideo(type){const v=$('#timingVideo'),fps=Math.max(1,num($('#videoFps').value,60)),time=num(v.currentTime);state.videoMarkers.push({type,time,frame:Math.round(time*fps),fps});save();renderVideo()}
function renderAddons(){const host=$('#addonList'),data=addons();if(!data.length)return host.innerHTML='<div class="empty">No skill add-ons registered.</div>';host.innerHTML=data.map((a,i)=>`<article class="row"><div class="row-title"><strong>${esc(a.skill||'Skill')}</strong><small>${esc(a.label||'Add-on')}</small></div><div class="cell" style="grid-column:span 3"><span>Effect</span><b>${esc(a.effect||'—')}</b></div><div class="actions"><button data-edit="${i}">Edit</button><button class="danger" data-del="${i}">Delete</button></div></article>`).join('');host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editAddon(+b.dataset.edit));host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{data.splice(+b.dataset.del,1);save();renderAddons()})}
function findSkill(name){return skills().find(s=>String(s.name).toLowerCase()===String(name).toLowerCase())}
function calcStats(){const sq=sequence(),ss=sq.map(findSkill).filter(Boolean);const damage=ss.reduce((a,s)=>a+skillDamage(s),0),duration=ss.reduce((a,s)=>a+Math.max(.01,num(s.duration,.5)),0),cc=ss.reduce((a,s)=>a+arr(s.cc).length,0),prot=ss.filter(s=>s.protection).length;return{skills:sq.length,damage,duration,dps:duration?damage/duration:0,cc,protection:ss.length?prot/ss.length:0}}
function renderBuilder(){const st=calcStats();$('#builderStats').innerHTML=[['Skills',st.skills],['Damage',Math.round(st.damage)],['Duration',st.duration.toFixed(3)+' s'],['Estimated DPS',Math.round(st.dps)],['CC effects',st.cc],['Protection',Math.round(st.protection*100)+'%']].map(x=>`<div class="stat-cell"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');const sq=sequence(),host=$('#comboSequence');host.innerHTML=sq.length?sq.map((n,i)=>`<span class="skill-chip">${i+1}. ${esc(n)}<button data-x="${i}">×</button></span>`).join(''):'<span class="empty" style="width:100%">Add skills or let AnalysisCore build a route.</span>';host.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{sq.splice(+b.dataset.x,1);save();renderBuilder()});renderSuggestions();renderCoach()}
function renderSuggestions(){const host=$('#suggestions');if(!suggestions.length)return host.innerHTML='<div class="empty">Run AnalysisCore to get suggestions.</div>';host.innerHTML=suggestions.map((s,i)=>`<article class="row" style="grid-template-columns:1fr 110px 130px"><div class="row-title"><strong>${i+1}. ${esc(s.skill||s.name||'Skill')}</strong><small>${esc(s.phase||'')} · score ${Number.isFinite(Number(s.score))?Number(s.score).toFixed(3):'—'}</small></div><div class="cell"><span>Damage</span><b>${Math.round(num(s.metrics?.damage))||'—'}</b></div><div class="actions"><button data-add="${i}">Add</button></div></article>`).join('');host.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const s=suggestions[+b.dataset.add];if(s?.skill)sequence().push(s.skill);save();renderBuilder()})}
function renderCoach(){const host=$('#coach');if(!coach.length){const p=state.prefs;return host.innerHTML=`<div class="coach-item"><strong>${p.combatMode.toUpperCase()} · ${p.profile}</strong><p>Coach explanations will use the active settings: damage focus ${p.damageFocus}, protection ${p.protectionPriority}, timing ${p.timingTolerance}, CC ${p.strictCC?'strict':'flexible'}.</p></div>`}host.innerHTML=coach.map(x=>`<div class="coach-item"><strong>${esc(x.title||x.kind||'Advice')}</strong><p>${esc(x.text||x.message||String(x))}</p></div>`).join('')}
async function analysis(action){const status=$('#analysisStatus');status.textContent='AnalysisCore running…';status.className='status-pill warn';try{const body={action,skills:skills().filter(s=>s.enabled!==false),transitions:transitions().filter(t=>t.enabled!==false),prefix:[...sequence()],preferences:state.prefs,limit:8};const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':ANON,'authorization':'Bearer '+ANON},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok===false)throw new Error(data.error||`HTTP ${r.status}`);if(action==='suggest')suggestions=Array.isArray(data.suggestions)?data.suggestions:[];else{const best=(data.results||[]).find(x=>Array.isArray(x.sequence));if(best){const q=sequence();q.splice(0,q.length,...best.sequence)}suggestions=Array.isArray(data.suggestions)?data.suggestions:[];save()}coach=Array.isArray(data.coach)?data.coach:Array.isArray(data.advice)?data.advice:[];status.textContent=`AnalysisCore · ${state.prefs.combatMode.toUpperCase()} · ${state.prefs.profile}`;status.className='status-pill good';renderBuilder()}catch(e){status.textContent='AnalysisCore: '+e.message;status.className='status-pill bad'}}
const presets={balanced:{profile:'balanced',combatMode:'pvp',strictCC:true,damageFocus:'balanced',ccFocus:'high',protectionPriority:'medium',timingTolerance:'normal',resourceDiscipline:'balanced'},'pvp-safe':{profile:'safe',combatMode:'pvp',strictCC:true,damageFocus:'balanced',ccFocus:'high',protectionPriority:'strict',timingTolerance:'tight',resourceDiscipline:'strict'},'pvp-burst':{profile:'aggressive',combatMode:'pvp',strictCC:true,damageFocus:'high',ccFocus:'high',protectionPriority:'medium',timingTolerance:'tight',resourceDiscipline:'balanced'},'pve-dps':{profile:'dps',combatMode:'pve',strictCC:false,damageFocus:'maximum',ccFocus:'low',protectionPriority:'low',timingTolerance:'normal',resourceDiscipline:'balanced'}};
function applyPreset(name){Object.assign(state.prefs,presets[name]||{});save();$$('#presetBar button').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));renderSettings();renderBuilder()}
const settingGroups=[['Mode & search',[['combatMode','Combat mode',['pvp','pve']],['profile','Analysis profile',['balanced','safe','aggressive','dps']],['searchDepth','Search depth',['fast','standard','deep']],['maxComboSkills','Maximum combo skills','number']]],['Combat priorities',[['damageFocus','Damage focus',['low','balanced','high','maximum']],['ccFocus','CC focus',['low','medium','high']],['protectionPriority','Protection priority',['low','medium','strict']],['strictCC','Strict CC','boolean']]],['Timing & transitions',[['timingTolerance','Timing tolerance',['loose','normal','tight']],['transitionPolicy','Transition policy',['all','measured','validated']],['cancelPolicy','Cancel policy',['all','measured','validated']],['protectionGaps','Protection gaps',['allow','avoid','strict']]],['Resources & confidence',[['resourceDiscipline','Resource discipline',['relaxed','balanced','strict']],['staminaReserve','Stamina reserve',['low','medium','high']],['resourceReserve','Resource reserve',['low','medium','high']],['confidence','Minimum confidence',['low','medium','high']],['missingData','Missing data',['permissive','cautious','strict']],['adviceStyle','Coach style',['concise','detailed','technical']]]];
function renderSettings(){const host=$('#settingsForm');host.innerHTML=settingGroups.map(([title,rows])=>`<section class="setting-group"><h2>${title}</h2>${rows.map(([k,label,type])=>`<label class="setting-row"><span>${label}</span>${settingControl(k,type)}</label>`).join('')}</section>`).join('');host.querySelectorAll('[data-setting]').forEach(el=>el.onchange=()=>{const k=el.dataset.setting;state.prefs[k]=el.type==='checkbox'?el.checked:el.type==='number'?num(el.value):el.value;save();renderBuilder()})}
function settingControl(k,type){const v=state.prefs[k];if(type==='boolean')return `<input data-setting="${k}" type="checkbox" ${v?'checked':''}>`;if(type==='number')return `<input data-setting="${k}" type="number" min="1" max="30" value="${num(v,10)}">`;return `<select data-setting="${k}">${type.map(x=>`<option value="${x}" ${x===v?'selected':''}>${x}</option>`).join('')}</select>`}
function dialog(title,fields,onSave){const d=$('#editorDialog'),box=$('#editorFields'),form=$('#editorForm');$('#editorTitle').textContent=title;box.innerHTML=fields.map(f=>`<label class="${f.wide?'wide':''}">${esc(f.label)}${f.type==='textarea'?`<textarea name="${f.name}">${esc(f.value??'')}</textarea>`:`<input name="${f.name}" type="${f.type||'text'}" value="${esc(f.value??'')}">`}</label>`).join('');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));onSave(fd);d.close()};d.showModal()}
function editSkill(i=null){const data=skills(),s=i==null?{}:data[i];dialog(i==null?'Add skill':'Edit skill',[{name:'name',label:'Name',value:s.name},{name:'phase',label:'Combat phase',value:s.phase},{name:'pveDamage',label:'PvE damage',type:'number',value:s.pveDamage},{name:'pvpDamage',label:'PvP damage',type:'number',value:s.pvpDamage},{name:'duration',label:'Duration (s)',type:'number',value:s.duration},{name:'cooldown',label:'Cooldown (s)',type:'number',value:s.cooldown},{name:'cc',label:'CC types, comma separated',value:arr(s.cc).join(', ')},{name:'ccAt',label:'CC applies at (s)',type:'number',value:s.ccAt},{name:'protection',label:'Protection',value:s.protection},{name:'staminaCost',label:'Stamina cost',type:'number',value:s.staminaCost}],fd=>{const x={...s,...fd,pveDamage:num(fd.pveDamage),pvpDamage:num(fd.pvpDamage),duration:num(fd.duration),cooldown:num(fd.cooldown),cc:arr(fd.cc),ccAt:fd.ccAt===''?null:num(fd.ccAt),staminaCost:num(fd.staminaCost),enabled:true};if(i==null)data.push(x);else data[i]=x;save();renderSkills();renderHome()})}
function editTransition(i=null,correct=false){const data=transitions(),t=i==null?{}:data[i];dialog(i==null?'Add transition':correct?'Correct transition':'Edit transition',[{name:'from',label:'From skill',value:t.from||t.fromSkill},{name:'to',label:'To skill',value:t.to||t.toSkill},{name:'timingSeconds',label:'Transition duration (s)',type:'number',value:t.timingSeconds},{name:'cancelAt',label:'Cancel point (s)',type:'number',value:t.cancelAt},{name:'entryOffset',label:'Entry skip (s)',type:'number',value:t.entryOffset},{name:'kind',label:'Type',value:t.kind||t.transitionType||'transition'}],fd=>{const x={...t,from:fd.from,to:fd.to,timingSeconds:fd.timingSeconds===''?null:num(fd.timingSeconds),cancelAt:fd.cancelAt===''?null:num(fd.cancelAt),entryOffset:fd.entryOffset===''?null:num(fd.entryOffset),kind:fd.kind,enabled:true,reviewStatus:correct?'corrected':(t.reviewStatus||'pending'),needsValidation:!correct,manualValidation:!!correct,reviewedAt:new Date().toISOString()};if(i==null)data.push(x);else data[i]=x;save();renderTransitions()})}
function editCombo(i=null){const data=combos(),c=i==null?{}:data[i];dialog(i==null?'Add combo':'Edit combo',[{name:'name',label:'Name',value:c.name},{name:'orientation',label:'Orientation',value:c.orientation||'PvP'},{name:'sequence',label:'Sequence, comma separated',wide:true,value:arr(c.sequence).join(', ')}],fd=>{const x={...c,name:fd.name,orientation:fd.orientation,sequence:arr(fd.sequence)};if(i==null)data.push(x);else data[i]=x;save();renderCombos()})}
function editAddon(i=null){const data=addons(),a=i==null?{}:data[i];dialog(i==null?'Add skill add-on':'Edit skill add-on',[{name:'skill',label:'Skill',value:a.skill},{name:'label',label:'Label',value:a.label},{name:'effect',label:'Effect',wide:true,value:a.effect}],fd=>{const x={...a,...fd};if(i==null)data.push(x);else data[i]=x;save();renderAddons()})}
document.addEventListener('DOMContentLoaded',init,{once:true});
})();